#!/bin/bash

# Note: The sleep 30 is very important.
# Because Packer is able to detect and SSH into the instance as soon as SSH is available,
# Ubuntu actually doesn't get proper amounts of time to initialize.
# The sleep makes sure that the OS properly initializes.
# https://www.packer.io/intro/getting-started/provision.html#configuring-provisioners
sleep 30
set +o +x

echo 'deb https://download.jitsi.org stable/' | sudo tee -a /etc/apt/sources.list.d/jitsi-stable.list
wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
sudo apt-add-repository universe
sudo apt-get update
sudo apt-get -y install debconf-utils nginx-full

# We pipe a single command at a time into debconf-set-selections to configure
# See `man debconf-set-selections`
echo jitsi-videobridge	jitsi-videobridge/jvb-hostname string	$CLIENT_DOMAIN | sudo debconf-set-selections
echo jitsi-meet-prosody	jitsi-videobridge/jvb-hostname string	$CLIENT_DOMAIN | sudo debconf-set-selections
echo "jitsi-meet-web-config	jitsi-meet/cert-choice select Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)" | sudo debconf-set-selections
echo jitsi-meet-web-config    jitsi-meet/cert-path-crt    string    /etc/ssl/$CLIENT_DOMAIN.crt | sudo debconf-set-selections
echo jitsi-meet-web-config    jitsi-meet/cert-path-key    string    /etc/ssl/$CLIENT_DOMAIN.key | sudo debconf-set-selections

sudo apt-get -y install jitsi-meet
sudo rm /usr/share/jitsi-meet/images/watermark.png

# Restart instance every PST midnight
sudo crontab -l > mycron
echo "0 7 * * * /usr/sbin/shutdown -r now" >> mycron
sudo crontab mycron
rm mycron
