#!/bin/bash

for i in "$@"
do
case $i in
    --client-domain=*)
    CLIENT_DOMAIN="${i#*=}"
    shift
    ;;
    --flush-dns-cache)
    FLUSH_DNS_CACHE=YES
    shift
    ;;
esac
done


# TODO: Figure out how to share the secrets safely and the terraform.tstate
# (push/pull from private bucket? Spin up a consul instance?)
(cd clients/$CLIENT_DOMAIN && terraform init &&
    terraform apply -var-file public.tfvars -var-file secrets.tfvars)

# Push the certbot install script that works for Ubuntu 20.04 to the server
if [ $FLUSH_DNS_CACHE ]; then
    echo "Flushing DNS cache"
    sudo killall -HUP mDNSResponder
fi
scp jitsi/install-letsencrypt-cert.sh ubuntu@$CLIENT_DOMAIN:
ssh -t ubuntu@$CLIENT_DOMAIN 'sudo ./install-letsencrypt-cert.sh'