// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PaymentFormController from "./payment_form_controller.js"
application.register("check-dropbox", PaymentFormController)

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import RoomFormController from "./room_form_controller.js"
application.register("room-form", RoomFormController)

import VideoRoomController from "./video_room_controller.js"
application.register("video-room", VideoRoomController)
