inherit_from: .rubocop_todo.yml

require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  pundit: config/rubocop-rspec.yml

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
