inherit_from: .rubocop_todo.yml

require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

inherit_gem:
  standard: config/base.yml
  pundit: config/rubocop-rspec.yml

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/bundle/**/*
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - db/schema.rb
