# From the following references:
#  - https://dev.to/github/publishing-a-docker-image-to-githubs-container-repository-4n50
#  - https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: build-publish-devcontainer
on:
  push:
    branches: ['main']
    paths:
      - .devcontainer/**
      - .ruby-version
      - Gemfile
jobs:
  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Build the convene-devcontainer Docker image
        run: |
            docker build --file .devcontainer/Dockerfile --tag ghcr.io/convene/convene-devcontainer:${GITHUB_REF#refs/heads/}.${GITHUB_SHA::6} .
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
